apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: customer-service
  name: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: customer-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: customer-service
    spec:
      containers:
        - image: registry.digitalocean.com/banking-system-registry/customer-service:latest
          name: customer-service
      imagePullSecrets:
        - name: registry-banking-system-registry
      restartPolicy: Always
