apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: customer-account
  name: customer-account
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: customer-account
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: customer-account
    spec:
      containers:
        - image: registry.digitalocean.com/banking-system-registry/customer-account:latest
          name: customer-account
      imagePullSecrets:
        - name: registry-banking-system-registry

      restartPolicy: Always
