version: '3.8'

services:
  mail-dev:
    container_name: maildev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    environment:
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_WEB_PORT=1080
    networks:
      - microservices-net

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./gateway
    ports:
      - "8866:8866"
    depends_on:
      - customer-service
      - customer-account
    networks:
      - banking-net


  customer-service:
    image: customer-service:latest
    build:
      context: ./customer
    networks:
      - banking-net

  customer-account:
    image: customer-account:latest
    build:
      context: ./customer-account
    networks:
      - banking-net
  config-server:
    image: config-server:latest
    build:
      context: ./configuration-server
    networks:
      - banking-net

  discovery-server:
    image: discovery-server:latest
    build:
      context: ./discovery-server
    networks:
      - banking-net

  notification-service:
    image: notification-service:latest
    build:
      context: ./notification-service
    networks:
      - banking-net


  transaction-service:
    image: transaction-service:latest
    build:
      context: ./transaction
    networks:
      - banking-net

  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: P@ssword123
      POSTGRES_DB: banking_db
    ports:
      - "5432:54332"
    networks:
      - banking-net



networks:
  microservices-net:
    driver: bridge
  banking-net:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
