version: '3.8'

services:
  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - microservices-net

  mysql-db:
    container_name: ms-mysql-db
    image: mysql:8.0
    environment:
      MYSQL_PASSWORD: paccy@123456789
      MYSQL_USER: test
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservices-net

  mongo-db:
    container_name: ms-mongo-db
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-net

  mongo-express:
    container_name: ms-mongo-express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: ms-mongo-db
    ports:
      - 8081:8081
    networks:
      - microservices-net

  pgadmin:
    container_name: ms-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    networks:
      - microservices-net

  zipkin:
    container_name: ms-zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - microservices-net

  kafka:
    container_name: ms-kafka
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - microservices-net

  zookeeper:
    container_name: ms-zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
