apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mail-dev
  name: mail-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mail-dev
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mail-dev
    spec:
      containers:
        - env:
            - name: MAILDEV_SMTP_PORT
              value: "1025"
            - name: MAILDEV_WEB_PORT
              value: "1080"
          image: maildev/maildev
          name: maildev
          ports:
            - containerPort: 1080
              protocol: TCP
            - containerPort: 1025
              protocol: TCP
      restartPolicy: Always
