apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postgres-db
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: postgres-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: banking_db
            - name: POSTGRES_PASSWORD
              value: P@ssword123
            - name: POSTGRES_USER
              value: banking
          image: postgres:15
          name: postgres-db
          ports:
            - containerPort: 54332
              protocol: TCP
      restartPolicy: Always
