spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: transaction-service

  messages:
    basename: i18n/messages

springdoc:
  swagger-ui:
    path: /swagger-ui.html
