spring:

  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: transaction-service

springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    org.springframework: DEBUG