apiVersion: v1
kind: Service
metadata:
  name: customer-account-service

spec:
  type: ClusterIP
  selector:
    app: customer-account-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8060
