spring:
  datasource:
    url: jdbc:h2:mem:customer_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true
      path: /h2-console


logging:
  level:
    org:
     springframework: DEBUG
