export const sidebarLinks =[
    {
        "icon":"/icons/Overview.svg",
        "label":"Overview",
        "route":"/dashboard"
    },
    {
        "icon":"/icons/wallet.svg",
        "label":"Balances",
        "route":"/balances"
    },
    {
        "icon":"/icons/Transaction.svg",
        "label":"Transactions",
        "route":"/transactions"
    },
    {
        "icon":"/icons/Bill.svg",
        "label":"Bills",
        "route":"/bills"
    },
    {
        "icon":"/icons/Overview.svg",
        "label":"Expenses",
        "route":"/expenses"
    },
    {
        "icon":"/icons/Goal.svg",
        "label":"Goals",
        "route":"/goals"
    },
    {
        "icon":"/icons/Settings.svg",
        "label":"Settings",
        "route":"/settings"
    }
]