spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: customer-account
          uri: lb:http://CUSTOMER-ACCOUNT
          predicates:
            - Path=/api/v1/account/**

        - id: notification-service
          uri: lb:http://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
        - id: transaction-service
          uri: lb:http://TRANSACTION-SERVICE
          predicates:
            - Path=/api/v1/transaction/**

server:
  port: 8866