spring:
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/transactions
    driver-class-name: org.postgresql.Driver
    username: paccy
    password: myPassword123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
server:
  port: 8070
